### ISSUE TITLE
Deploy using hedy

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-rum-collector#191]
Refactor to use `helix-universal` then deploy using `helix-deploy`

**Comment by bosschaert** [comment]
Sharing some progress here...

After running 

```
npm run build
```

I can deploy `bin/index.js` into Fastly Compute via `hedy` with:

```
hedy --build --verbose --directory `pwd`/temp --entryFile `pwd`/bin/index.js --deploy --fastly-auth <apikey> --compute-service-id <serviceid> --compute-test-domain <service-domain> --target c@e --arch node --arch edge --fastly-gateway deploy-test.anywhere.run
```

Then you can call it with something like this:
```
$ curl --header 'X-Forwarded-Host:example.com' -X POST https://<service-domain>.edgecompute.app/.rum/1  -d '{"cwv":{ "CLS": 1.0, "LCP": 1.0, "FID": 4 }, "id": "blablub", "weight": 2}'
rum collected.
```

## Next steps:
The `hedy` command does produce the following error:

```
ERROR in fastly:logger
Module build failed: UnhandledSchemeError: Reading from "fastly:logger" is not handled by plugins (Unhandled scheme).
```

This means that either the hedy command needs to be updated to handle the special fastly:logger import.
Or - as it might be that this happens during the generation of the main.wasm file, and the main.wasm file is already generated during `npm run build`, maybe we can give hedy that file directly so that it doesn't have to handle this special import...
